output: /path/to/orenza/workdir
input_database: /path/where/final/db/is/saved/db_orenza.sqlite3 # nothing if start from scratch
tmpdir: /tmp

download:
  explorenz: true
  sprot: true
  trembl: true
  kegg: true
  brenda: true
  pdb: true

explorenz:
  url: https://www.enzyme-database.org/downloads/enzyme-data.xml.gz
  output_file: explorenz_data.xml.gz

uniprot:
  ftp: ftp.expasy.org
  remote_file: /databases/uniprot/current_release/knowledgebase/complete/reldate.txt
  output_file: uniprot_reldate.txt

sprot:
  ftp: ftp.expasy.org
  remote_file: /databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.dat.gz
  output_file: sprot.dat.gz

trembl:
  ftp: ftp.expasy.org
  remote_file: /databases/uniprot/current_release/knowledgebase/complete/uniprot_trembl.dat.gz
  output_file: trembl.dat.gz

kegg:
  url: https://www.genome.jp/kegg/pathway.html

# To download here : https://www.brenda-enzymes.org/download.php (require manual validation for dl)
brenda:
  compressed_file: /path/to/brenda_2023_1.txt.tar.gz

pdb:
  url: https://files.rcsb.org/pub/pdb/data/structures/divided/XML/
  # multithreading
  worker: 500
