output: /home/demonz/programmation/stage/orenza/af2_web/bioi2server/orenza/script/
database: /home/demonz/programmation/stage/orenza/af2_web/bioi2server/orenza/script/db/db_orenza.sqlite3

explorenz:
  url: https://www.enzyme-database.org/downloads/enzyme-data.xml.gz
  output_file: explorenz_data.xml.gz

sprot:
  ftp: ftp.expasy.org
  remote_file: /databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.dat.gz
  output_file: sprot.dat.gz

trembl:
  ftp: ftp.expasy.org
  remote_file: /databases/uniprot/current_release/knowledgebase/complete/uniprot_trembl.dat.gz
  output_file: trembl.dat.gz

kegg:
  url: https://www.genome.jp/kegg/pathway.html

brenda:
  compressed_file: brenda_2023_1.txt.tar.gz

pdb:
  url: https://files.rcsb.org/pub/pdb/data/structures/divided/XML/
  worker: 500
