# comment
download_folder: /home/demonz/programmation/stage/orenza/af2_web/bioi2server/orenza
database : /home/demonz/programmation/stage/orenza/af2_web/bioi2server/orenza/script/test.sqlite3
explorenz:
  download: 
    function: http
    args:
      url: https://www.enzyme-database.org/downloads/enzyme-data.xml.gz
      filename: explorenz_data.xml.gz
  parsing:
    function: explorenz
    args: 
      filename: explorenz_data.gz.xml
      path: .
  populate: 
    function: explorenz
    args:
     filename: /home/demonz/programmation/stage/orenza/af2_web/bioi2server/orenza/data/pickle/explorenz.pickle
     database_name: /home/demonz/programmation/stage/orenza/af2_web/bioi2server/orenza/script/test.sqlite3
      #sprot:
      #  download:
      #    function: ftp
      #    args:
      #      url : "google.fr"




